### ISSUE TITLE
Arc Rifle = Plasma Caliver

### ISSUE THREAD

**Issue by ghost** [Kykuy/40k-ancient-viewer#1]
The app shows one of the weapons as "Arc Rifle", but it is really the tech-adept's "Plasma Caliver" (though the game file lists it as arc_rifle, so that is likely why it appears as such). The Sheets document (https://docs.google.com/spreadsheets/d/1SsMOf-6jhhhly36s2pf7aqWO96Y15lVN2alulkMJX1s/edit#gid=1326208625) that seems to be the source of the information actually has it correct in the "Ancient Relic Viewer" tab, so I am guessing a name just needs to be converted somewhere in the javascript or html.

**Comment by Kykuy** [comment]
Yeah I've never really played Techpriest and Arc Rifle is also a weapon in 40k so I left is as such. Good to know, thanks.
Should be fixed now and is for me in the live version. Feel free to comment if it isn't.
